// Generated by CoffeeScript 1.6.3
var GoogleStrategy, app, express, http, passport, path, strategy;

express = require('express');

http = require('http');

path = require('path');

passport = require('passport');

GoogleStrategy = require('passport-google').Strategy;

app = express();

strategy = new GoogleStrategy({
  returnURL: 'https://sephirotictree.herokuapp.com/auth/google/return',
  realm: 'https://sephirotictree.herokuapp.com/'
}, function(identifier, profile, done) {
  return User.findOrCreate({
    openId: identifier
  }, function(err, user) {
    return done(err, user);
  });
});

passport.use(strategy);

app.set('port', process.env.PORT || 3000);

app.all('*', function(req, res, next) {
  if (req.headers['x-forwarded-proto'] !== 'https') {
    return res.redirect("https://" + req.host + req.url);
  } else {
    return next();
  }
});

app.get('/auth/google', passport.authenticate('google'));

app.get('/auth/google/return', passport.authenticate('google', {
  successRedirect: '/',
  failureRedirect: '/login'
}));

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(express.compress());

app.use(app.router);

app.use(express["static"](path.join(__dirname, 'public')));

http.createServer(app).listen(app.get('port'), function() {
  return console.log("Express server listening on port  + " + (app.get('port')));
});
