// Generated by CoffeeScript 1.6.3
var app, express, http, path;

express = require('express');

http = require('http');

path = require('path');

app = express();

app.set('port', process.env.PORT || 3000);

app.all('*', function(req, res, next) {
  if (req.headers['x-forwarded-proto'] !== 'https') {
    return res.redirect("https://" + req.host + req.url);
  } else {
    return next();
  }
});

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(express.compress());

app.use(app.router);

app.use(express["static"](path.join(__dirname, 'public')));

http.createServer(app).listen(app.get('port'), function() {
  return console.log("Express server listening on port  + " + (app.get('port')));
});
